# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fbeaf094443cc1e6489641132559bf73d9ccd93daa29986865354590bf3fdb356673f7343fd2c02cf8eed17dc94e9f8f4fc98407cf0052df053398df4f0484b
test:
  secret_key_base: dc34ff10fc4839fb825ca9ee5cc7b510719c542e488f08e6f8c81555359c7d88c5a24722e548fd5280f8b69ed1c6b711c4ca53788b3573fc16c9a8a9b20b9cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
